#-------------------------------------------------
#
# Project created by QtCreator 2023-01-03T21:12:32
#
#-------------------------------------------------

QT       += core gui
QT += network

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = SmartPicker
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

LIBS += /usr/local/lib/libopencv_* -lwiringPi -lcrypt -lpthread -lm -lrt
#LIBS += /home/orangepi/Downloads/opencv-4.1.0/build/lib/libopencv_*

INCLUDEPATH += /usr/local/include \
                /usr/local/include/opencv4/opencv2 \
                ../../../mechanicalArmOp/inc \
                ../../../lib/eigen-3.3.9/Eigen \
                ../../../lib/json/include\
                ../../../GA_PSO/src/GeneticAlgorithm

DISTFILES += \
    ../binocularCamera/extrinsics.yml \
    ../binocularCamera/intrinsics.yml

HEADERS += \
    ../../../GA_PSO/src/GeneticAlgorithm/Utils/GlobalCppRandomEngine.h \
    ../../../GA_PSO/src/GeneticAlgorithm/Chromosome.h \
    ../../../GA_PSO/src/GeneticAlgorithm/ChromosomeFactory.h \
    ../../../GA_PSO/src/GeneticAlgorithm/MainProcess.h \
    ../../../GA_PSO/src/GeneticAlgorithm/Multithreading.h \
    ../../../GA_PSO/src/GeneticAlgorithm/Population.h \
    ../../../GA_PSO/src/GeneticAlgorithm/PopulationFactory.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Cholesky/LDLT.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Cholesky/LLT.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Cholesky/LLT_LAPACKE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/CholmodSupport/CholmodSupport.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/AltiVec/Complex.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/AltiVec/PacketMath.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/AVX/Complex.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/AVX/MathFunctions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/AVX/PacketMath.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/AVX/TypeCasting.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/AVX512/MathFunctions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/AVX512/PacketMath.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/CUDA/Complex.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/CUDA/Half.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/CUDA/MathFunctions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/CUDA/PacketMath.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/CUDA/TypeCasting.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/Default/ConjHelper.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/Default/Settings.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/NEON/Complex.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/NEON/MathFunctions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/NEON/PacketMath.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/SSE/Complex.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/SSE/MathFunctions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/SSE/PacketMath.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/SSE/TypeCasting.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/ZVector/Complex.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/ZVector/MathFunctions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/arch/ZVector/PacketMath.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/functors/AssignmentFunctors.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/functors/BinaryFunctors.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/functors/NullaryFunctors.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/functors/StlFunctors.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/functors/TernaryFunctors.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/functors/UnaryFunctors.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/GeneralMatrixMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/GeneralMatrixVector.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/Parallelizer.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/SelfadjointMatrixVector.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/SelfadjointProduct.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/SelfadjointRank2Update.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/TriangularMatrixMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/TriangularMatrixVector.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/TriangularSolverMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/products/TriangularSolverVector.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/BlasUtil.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/Constants.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/DisableStupidWarnings.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/ForwardDeclarations.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/Macros.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/Memory.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/Meta.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/MKL_support.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/NonMPL2.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/ReenableStupidWarnings.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/StaticAssert.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/util/XprHelper.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Array.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/ArrayBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/ArrayWrapper.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Assign.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Assign_MKL.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/AssignEvaluator.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/BandMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Block.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/BooleanRedux.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/CommaInitializer.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/ConditionEstimator.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/CoreEvaluators.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/CoreIterators.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/CwiseBinaryOp.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/CwiseNullaryOp.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/CwiseTernaryOp.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/CwiseUnaryOp.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/CwiseUnaryView.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/DenseBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/DenseCoeffsBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/DenseStorage.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Diagonal.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/DiagonalMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/DiagonalProduct.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Dot.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/EigenBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/ForceAlignedAccess.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Fuzzy.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/GeneralProduct.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/GenericPacketMath.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/GlobalFunctions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Inverse.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/IO.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Map.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/MapBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/MathFunctions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/MathFunctionsImpl.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Matrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/MatrixBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/NestByValue.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/NoAlias.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/NumTraits.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/PermutationMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/PlainObjectBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Product.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/ProductEvaluators.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Random.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Redux.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Ref.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Replicate.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/ReturnByValue.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Reverse.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Select.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/SelfAdjointView.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/SelfCwiseBinaryOp.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Solve.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/SolverBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/SolveTriangular.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/StableNorm.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Stride.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Swap.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Transpose.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Transpositions.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/TriangularMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/VectorBlock.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/VectorwiseOp.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Core/Visitor.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/ComplexSchur.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/EigenSolver.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/RealQZ.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/RealSchur.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Eigenvalues/Tridiagonalization.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/arch/Geometry_SSE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/AlignedBox.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/AngleAxis.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/EulerAngles.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/Homogeneous.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/Hyperplane.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/OrthoMethods.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/ParametrizedLine.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/Quaternion.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/Rotation2D.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/RotationBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/Scaling.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/Transform.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/Translation.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Geometry/Umeyama.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Householder/BlockHouseholder.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Householder/Householder.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Householder/HouseholderSequence.h \
    ../../../lib/eigen-3.3.9/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
    ../../../lib/eigen-3.3.9/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
    ../../../lib/eigen-3.3.9/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
    ../../../lib/eigen-3.3.9/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
    ../../../lib/eigen-3.3.9/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
    ../../../lib/eigen-3.3.9/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
    ../../../lib/eigen-3.3.9/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
    ../../../lib/eigen-3.3.9/Eigen/src/Jacobi/Jacobi.h \
    ../../../lib/eigen-3.3.9/Eigen/src/LU/arch/Inverse_SSE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/LU/Determinant.h \
    ../../../lib/eigen-3.3.9/Eigen/src/LU/FullPivLU.h \
    ../../../lib/eigen-3.3.9/Eigen/src/LU/InverseImpl.h \
    ../../../lib/eigen-3.3.9/Eigen/src/LU/PartialPivLU.h \
    ../../../lib/eigen-3.3.9/Eigen/src/LU/PartialPivLU_LAPACKE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/MetisSupport/MetisSupport.h \
    ../../../lib/eigen-3.3.9/Eigen/src/misc/blas.h \
    ../../../lib/eigen-3.3.9/Eigen/src/misc/Image.h \
    ../../../lib/eigen-3.3.9/Eigen/src/misc/Kernel.h \
    ../../../lib/eigen-3.3.9/Eigen/src/misc/lapack.h \
    ../../../lib/eigen-3.3.9/Eigen/src/misc/lapacke.h \
    ../../../lib/eigen-3.3.9/Eigen/src/misc/lapacke_mangling.h \
    ../../../lib/eigen-3.3.9/Eigen/src/misc/RealSvd2x2.h \
    ../../../lib/eigen-3.3.9/Eigen/src/OrderingMethods/Amd.h \
    ../../../lib/eigen-3.3.9/Eigen/src/OrderingMethods/Eigen_Colamd.h \
    ../../../lib/eigen-3.3.9/Eigen/src/OrderingMethods/Ordering.h \
    ../../../lib/eigen-3.3.9/Eigen/src/PardisoSupport/PardisoSupport.h \
    ../../../lib/eigen-3.3.9/Eigen/src/PaStiXSupport/PaStiXSupport.h \
    ../../../lib/eigen-3.3.9/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
    ../../../lib/eigen-3.3.9/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
    ../../../lib/eigen-3.3.9/Eigen/src/plugins/BlockMethods.h \
    ../../../lib/eigen-3.3.9/Eigen/src/plugins/CommonCwiseBinaryOps.h \
    ../../../lib/eigen-3.3.9/Eigen/src/plugins/CommonCwiseUnaryOps.h \
    ../../../lib/eigen-3.3.9/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
    ../../../lib/eigen-3.3.9/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
    ../../../lib/eigen-3.3.9/Eigen/src/QR/ColPivHouseholderQR.h \
    ../../../lib/eigen-3.3.9/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
    ../../../lib/eigen-3.3.9/Eigen/src/QR/FullPivHouseholderQR.h \
    ../../../lib/eigen-3.3.9/Eigen/src/QR/HouseholderQR.h \
    ../../../lib/eigen-3.3.9/Eigen/src/QR/HouseholderQR_LAPACKE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCholesky/SimplicialCholesky.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/AmbiVector.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/CompressedStorage.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/MappedSparseMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseAssign.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseBlock.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseColEtree.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseCompressedBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseDenseProduct.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseDiagonalProduct.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseDot.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseFuzzy.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseMap.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseMatrixBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparsePermutation.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseProduct.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseRedux.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseRef.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseSelfAdjointView.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseSolverBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseTranspose.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseTriangularView.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseUtil.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseVector.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/SparseView.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseCore/TriangularSolver.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_column_bmod.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_column_dfs.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_Memory.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_panel_bmod.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_panel_dfs.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_pivotL.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_pruneL.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_relax_snode.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_Structs.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLU_Utils.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseLU/SparseLUImpl.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SparseQR/SparseQR.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
    ../../../lib/eigen-3.3.9/Eigen/src/StlSupport/details.h \
    ../../../lib/eigen-3.3.9/Eigen/src/StlSupport/StdDeque.h \
    ../../../lib/eigen-3.3.9/Eigen/src/StlSupport/StdList.h \
    ../../../lib/eigen-3.3.9/Eigen/src/StlSupport/StdVector.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SuperLUSupport/SuperLUSupport.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SVD/BDCSVD.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SVD/JacobiSVD.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SVD/SVDBase.h \
    ../../../lib/eigen-3.3.9/Eigen/src/SVD/UpperBidiagonalization.h \
    ../../../lib/eigen-3.3.9/Eigen/src/UmfPackSupport/UmfPackSupport.h \
    ../../../lib/eigen-3.3.9/Eigen/Cholesky \
    ../../../lib/eigen-3.3.9/Eigen/CholmodSupport \
    ../../../lib/eigen-3.3.9/Eigen/Core \
    ../../../lib/eigen-3.3.9/Eigen/Dense \
    ../../../lib/eigen-3.3.9/Eigen/Eigen \
    ../../../lib/eigen-3.3.9/Eigen/Eigenvalues \
    ../../../lib/eigen-3.3.9/Eigen/Geometry \
    ../../../lib/eigen-3.3.9/Eigen/Householder \
    ../../../lib/eigen-3.3.9/Eigen/IterativeLinearSolvers \
    ../../../lib/eigen-3.3.9/Eigen/Jacobi \
    ../../../lib/eigen-3.3.9/Eigen/LU \
    ../../../lib/eigen-3.3.9/Eigen/MetisSupport \
    ../../../lib/eigen-3.3.9/Eigen/OrderingMethods \
    ../../../lib/eigen-3.3.9/Eigen/PardisoSupport \
    ../../../lib/eigen-3.3.9/Eigen/PaStiXSupport \
    ../../../lib/eigen-3.3.9/Eigen/QR \
    ../../../lib/eigen-3.3.9/Eigen/QtAlignedMalloc \
    ../../../lib/eigen-3.3.9/Eigen/Sparse \
    ../../../lib/eigen-3.3.9/Eigen/SparseCholesky \
    ../../../lib/eigen-3.3.9/Eigen/SparseCore \
    ../../../lib/eigen-3.3.9/Eigen/SparseLU \
    ../../../lib/eigen-3.3.9/Eigen/SparseQR \
    ../../../lib/eigen-3.3.9/Eigen/SPQRSupport \
    ../../../lib/eigen-3.3.9/Eigen/StdDeque \
    ../../../lib/eigen-3.3.9/Eigen/StdList \
    ../../../lib/eigen-3.3.9/Eigen/StdVector \
    ../../../lib/eigen-3.3.9/Eigen/SuperLUSupport \
    ../../../lib/eigen-3.3.9/Eigen/SVD \
    ../../../lib/eigen-3.3.9/Eigen/UmfPackSupport \
    ../../../lib/json/include/nlohmann/detail/conversions/from_json.hpp \
    ../../../lib/json/include/nlohmann/detail/conversions/to_chars.hpp \
    ../../../lib/json/include/nlohmann/detail/conversions/to_json.hpp \
    ../../../lib/json/include/nlohmann/detail/input/binary_reader.hpp \
    ../../../lib/json/include/nlohmann/detail/input/input_adapters.hpp \
    ../../../lib/json/include/nlohmann/detail/input/json_sax.hpp \
    ../../../lib/json/include/nlohmann/detail/input/lexer.hpp \
    ../../../lib/json/include/nlohmann/detail/input/parser.hpp \
    ../../../lib/json/include/nlohmann/detail/input/position_t.hpp \
    ../../../lib/json/include/nlohmann/detail/iterators/internal_iterator.hpp \
    ../../../lib/json/include/nlohmann/detail/iterators/iter_impl.hpp \
    ../../../lib/json/include/nlohmann/detail/iterators/iteration_proxy.hpp \
    ../../../lib/json/include/nlohmann/detail/iterators/iterator_traits.hpp \
    ../../../lib/json/include/nlohmann/detail/iterators/json_reverse_iterator.hpp \
    ../../../lib/json/include/nlohmann/detail/iterators/primitive_iterator.hpp \
    ../../../lib/json/include/nlohmann/detail/meta/call_std/begin.hpp \
    ../../../lib/json/include/nlohmann/detail/meta/call_std/end.hpp \
    ../../../lib/json/include/nlohmann/detail/meta/cpp_future.hpp \
    ../../../lib/json/include/nlohmann/detail/meta/detected.hpp \
    ../../../lib/json/include/nlohmann/detail/meta/identity_tag.hpp \
    ../../../lib/json/include/nlohmann/detail/meta/is_sax.hpp \
    ../../../lib/json/include/nlohmann/detail/meta/std_fs.hpp \
    ../../../lib/json/include/nlohmann/detail/meta/type_traits.hpp \
    ../../../lib/json/include/nlohmann/detail/meta/void_t.hpp \
    ../../../lib/json/include/nlohmann/detail/output/binary_writer.hpp \
    ../../../lib/json/include/nlohmann/detail/output/output_adapters.hpp \
    ../../../lib/json/include/nlohmann/detail/output/serializer.hpp \
    ../../../lib/json/include/nlohmann/detail/abi_macros.hpp \
    ../../../lib/json/include/nlohmann/detail/exceptions.hpp \
    ../../../lib/json/include/nlohmann/detail/hash.hpp \
    ../../../lib/json/include/nlohmann/detail/json_custom_base_class.hpp \
    ../../../lib/json/include/nlohmann/detail/json_pointer.hpp \
    ../../../lib/json/include/nlohmann/detail/json_ref.hpp \
    ../../../lib/json/include/nlohmann/detail/macro_scope.hpp \
    ../../../lib/json/include/nlohmann/detail/macro_unscope.hpp \
    ../../../lib/json/include/nlohmann/detail/string_concat.hpp \
    ../../../lib/json/include/nlohmann/detail/string_escape.hpp \
    ../../../lib/json/include/nlohmann/detail/value_t.hpp \
    ../../../lib/json/include/nlohmann/thirdparty/hedley/hedley.hpp \
    ../../../lib/json/include/nlohmann/thirdparty/hedley/hedley_undef.hpp \
    ../../../lib/json/include/nlohmann/adl_serializer.hpp \
    ../../../lib/json/include/nlohmann/byte_container_with_subtype.hpp \
    ../../../lib/json/include/nlohmann/json.hpp \
    ../../../lib/json/include/nlohmann/json_fwd.hpp \
    ../../../lib/json/include/nlohmann/ordered_map.hpp \
    ../../../mechanicalArmOp/inc/DH_MechanicalArm.h \
    ../../../mechanicalArmOp/inc/MechanicalArm.h \
    ../../../mechanicalArmOp/inc/TransferMatrix.h \
    ../binocularCamera/binocularCamera.h \
    ../controller/armController.h \
    ../controller/PinController.h \
    ../networkHandle/MqttHandle.h \
    ../Pointer/Exception.h \
    ../Pointer/Object.h \
    ../Pointer/Pointer.h \
    ../Pointer/SharedPointer.h \
    ../Pointer/SmartPointer.h \
    ../qmqtt/qmqtt.h \
    ../qmqtt/qmqtt_client.h \
    ../qmqtt/qmqtt_client_p.h \
    ../qmqtt/qmqtt_frame.h \
    ../qmqtt/qmqtt_global.h \
    ../qmqtt/qmqtt_message.h \
    ../qmqtt/qmqtt_message_p.h \
    ../qmqtt/qmqtt_network_p.h \
    ../qmqtt/qmqtt_networkinterface.h \
    ../qmqtt/qmqtt_routedmessage.h \
    ../qmqtt/qmqtt_router.h \
    ../qmqtt/qmqtt_routesubscription.h \
    ../qmqtt/qmqtt_socket_p.h \
    ../qmqtt/qmqtt_socketinterface.h \
    ../qmqtt/qmqtt_ssl_socket_p.h \
    ../qmqtt/qmqtt_timer_p.h \
    ../qmqtt/qmqtt_timerinterface.h \
    ../qmqtt/qmqtt_websocket_p.h \
    ../qmqtt/qmqtt_websocketiodevice_p.h \
    ../serial/AbstractSerial.h \
    ../serial/Serial.h \
    ../serial/wiringSerial.h \
    SmartPicker.h

SOURCES += \
    ../../../GA_PSO/src/GeneticAlgorithm/Utils/GlobalCppRandomEngine.cpp \
    ../../../GA_PSO/src/GeneticAlgorithm/Chromosome.cpp \
    ../../../GA_PSO/src/GeneticAlgorithm/ChromosomeFactory.cpp \
    ../../../GA_PSO/src/GeneticAlgorithm/MainProcess.cpp \
    ../../../GA_PSO/src/GeneticAlgorithm/Multithreading.cpp \
    ../../../GA_PSO/src/GeneticAlgorithm/Population.cpp \
    ../../../GA_PSO/src/GeneticAlgorithm/PopulationFactory.cpp \
    ../../../mechanicalArmOp/src/TransferMatrix.cpp \
    ../binocularCamera/binocularCamera.cpp \
    ../controller/armController.cpp \
    ../controller/PinController.cpp \
    ../networkHandle/MqttHandle.cpp \
    ../Pointer/Exception.cpp \
    ../Pointer/Object.cpp \
    ../qmqtt/qmqtt_client.cpp \
    ../qmqtt/qmqtt_client_p.cpp \
    ../qmqtt/qmqtt_frame.cpp \
    ../qmqtt/qmqtt_message.cpp \
    ../qmqtt/qmqtt_network.cpp \
    ../qmqtt/qmqtt_router.cpp \
    ../qmqtt/qmqtt_routesubscription.cpp \
    ../qmqtt/qmqtt_socket.cpp \
    ../qmqtt/qmqtt_ssl_socket.cpp \
    ../qmqtt/qmqtt_timer.cpp \
    ../qmqtt/qmqtt_websocket.cpp \
    ../qmqtt/qmqtt_websocketiodevice.cpp \
    ../serial/Serial.cpp \
    main.cpp \
    SmartPicker.cpp \
    ../serial/wiringSerial.c



